use_frameworks!

platform :ios, '9.0'

target 'taskSpec_Example' do
  pod 'taskSpec', :path => '../'

  target 'taskSpec_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
